whenever sqlerror exit failure rollback;

BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_FIRST_COURSE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FIRST_COURSE_RECORD CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_REPORT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_CHARGE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_MEDICAL_ORDER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_ENCOUNTER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

CREATE TABLE HIS_ENCOUNTER (
  PATIENT_ID              VARCHAR2(64) NOT NULL,
  VISIT_ID                VARCHAR2(64) NOT NULL,
  HOSPITAL_NAME           VARCHAR2(200) NOT NULL,
  PATIENT_NAME            VARCHAR2(100) NOT NULL,
  GENDER                  VARCHAR2(2 CHAR) NOT NULL,
  AGE                     NUMBER(3) NOT NULL,
  WARD_NAME               VARCHAR2(200) NOT NULL,
  BED_NUMBER              VARCHAR2(50) NOT NULL,
  INPATIENT_NO            VARCHAR2(64) NOT NULL,
  ADMITTED_AT             TIMESTAMP WITH TIME ZONE NOT NULL,
  RECORDED_AT             TIMESTAMP WITH TIME ZONE NOT NULL,
  ILLNESS_ONSET_COURSE    VARCHAR2(4000) NOT NULL,
  PRIMARY_SYMPTOMS        VARCHAR2(4000) NOT NULL,
  PAST_MEDICAL_HISTORY    VARCHAR2(4000) NOT NULL,
  PHYSICAL_EXAMINATION    VARCHAR2(4000) NOT NULL,
  DIAGNOSIS_BASIS         VARCHAR2(4000) NOT NULL,
  DIFFERENTIAL_DIAGNOSIS  VARCHAR2(4000) NOT NULL,
  CASE_CLASSIFICATION     VARCHAR2(1000),
  ATTENDING_PHYSICIAN     VARCHAR2(100) NOT NULL,
  AUTHOR_PHYSICIAN        VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_HIS_ENCOUNTER PRIMARY KEY (PATIENT_ID, VISIT_ID),
  CONSTRAINT CK_HIS_GENDER CHECK (GENDER IN ('男', '女', '未知')),
  CONSTRAINT CK_HIS_AGE CHECK (AGE BETWEEN 0 AND 150)
);

CREATE TABLE HIS_MEDICAL_ORDER (
  PATIENT_ID     VARCHAR2(64) NOT NULL,
  VISIT_ID       VARCHAR2(64) NOT NULL,
  ORDER_SEQUENCE NUMBER(3) NOT NULL,
  ORDER_CONTENT  VARCHAR2(4000) NOT NULL,
  CONSTRAINT PK_HIS_MEDICAL_ORDER PRIMARY KEY (PATIENT_ID, VISIT_ID, ORDER_SEQUENCE),
  CONSTRAINT FK_ORDER_ENCOUNTER FOREIGN KEY (PATIENT_ID, VISIT_ID)
    REFERENCES HIS_ENCOUNTER (PATIENT_ID, VISIT_ID)
);

CREATE TABLE HIS_CHARGE (
  PATIENT_ID     VARCHAR2(64) NOT NULL,
  VISIT_ID       VARCHAR2(64) NOT NULL,
  CHARGE_SEQUENCE NUMBER(3) NOT NULL,
  ITEM_NAME      VARCHAR2(500) NOT NULL,
  AMOUNT         NUMBER(12, 2),
  CONSTRAINT PK_HIS_CHARGE PRIMARY KEY (PATIENT_ID, VISIT_ID, CHARGE_SEQUENCE),
  CONSTRAINT FK_CHARGE_ENCOUNTER FOREIGN KEY (PATIENT_ID, VISIT_ID)
    REFERENCES HIS_ENCOUNTER (PATIENT_ID, VISIT_ID)
);

CREATE TABLE HIS_REPORT (
  PATIENT_ID      VARCHAR2(64) NOT NULL,
  VISIT_ID        VARCHAR2(64) NOT NULL,
  REPORT_SEQUENCE NUMBER(3) NOT NULL,
  REPORT_TYPE     VARCHAR2(100) NOT NULL,
  REPORT_NAME     VARCHAR2(200) NOT NULL,
  REPORT_RESULT   VARCHAR2(4000) NOT NULL,
  CONSTRAINT PK_HIS_REPORT PRIMARY KEY (PATIENT_ID, VISIT_ID, REPORT_SEQUENCE),
  CONSTRAINT FK_REPORT_ENCOUNTER FOREIGN KEY (PATIENT_ID, VISIT_ID)
    REFERENCES HIS_ENCOUNTER (PATIENT_ID, VISIT_ID)
);

CREATE TABLE FIRST_COURSE_RECORD (
  PATIENT_ID VARCHAR2(64) NOT NULL,
  VISIT_ID   VARCHAR2(64) NOT NULL,
  RECORD_XML CLOB NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_FIRST_COURSE_RECORD PRIMARY KEY (PATIENT_ID, VISIT_ID)
);

CREATE OR REPLACE PACKAGE PKG_FIRST_COURSE AS
  PROCEDURE UPSERT_RECORD(
    P_PATIENT_ID IN VARCHAR2,
    P_VISIT_ID IN VARCHAR2,
    P_RECORD_XML IN CLOB,
    P_RESULT OUT VARCHAR2
  );
END PKG_FIRST_COURSE;
/

CREATE OR REPLACE PACKAGE BODY PKG_FIRST_COURSE AS
  PROCEDURE UPSERT_RECORD(
    P_PATIENT_ID IN VARCHAR2,
    P_VISIT_ID IN VARCHAR2,
    P_RECORD_XML IN CLOB,
    P_RESULT OUT VARCHAR2
  ) AS
  BEGIN
    MERGE INTO FIRST_COURSE_RECORD TARGET
    USING (SELECT P_PATIENT_ID AS PATIENT_ID, P_VISIT_ID AS VISIT_ID, P_RECORD_XML AS RECORD_XML FROM DUAL) SOURCE
      ON (TARGET.PATIENT_ID = SOURCE.PATIENT_ID AND TARGET.VISIT_ID = SOURCE.VISIT_ID)
    WHEN MATCHED THEN UPDATE SET
      TARGET.RECORD_XML = SOURCE.RECORD_XML,
      TARGET.UPDATED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (PATIENT_ID, VISIT_ID, RECORD_XML)
      VALUES (SOURCE.PATIENT_ID, SOURCE.VISIT_ID, SOURCE.RECORD_XML);

    P_RESULT := 'SUCCESS';
  END UPSERT_RECORD;
END PKG_FIRST_COURSE;
/

INSERT INTO HIS_ENCOUNTER (
  PATIENT_ID, VISIT_ID, HOSPITAL_NAME, PATIENT_NAME, GENDER, AGE, WARD_NAME, BED_NUMBER, INPATIENT_NO,
  ADMITTED_AT, RECORDED_AT, ILLNESS_ONSET_COURSE, PRIMARY_SYMPTOMS, PAST_MEDICAL_HISTORY, PHYSICAL_EXAMINATION,
  DIAGNOSIS_BASIS, DIFFERENTIAL_DIAGNOSIS, CASE_CLASSIFICATION, ATTENDING_PHYSICIAN, AUTHOR_PHYSICIAN
) VALUES (
  'CASE-001', 'TEST20260811001', '示例市第一医院', '患者甲', '男', 27, '普外科一病区', '12A', 'TEST20260811001',
  TO_TIMESTAMP_TZ('2026-08-11 08:00:00 +08:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
  TO_TIMESTAMP_TZ('2026-08-11 08:35:00 +08:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
  '患者约18小时前出现脐周隐痛，6小时前疼痛转移并固定于右下腹，逐渐加重。',
  '右下腹持续性疼痛，伴恶心，未呕吐，无寒战。',
  '否认高血压、糖尿病及手术史，否认药物过敏。',
  '体温37.8℃；右下腹麦氏点压痛、反跳痛，腹肌轻度紧张，肠鸣音存在。',
  '转移性右下腹痛伴麦氏点压痛及炎症指标升高，影像提示阑尾增粗。',
  '需与右侧输尿管结石、急性胃肠炎及梅克尔憩室炎鉴别。',
  '急性单纯性阑尾炎待进一步评估。', '医生甲', '医生乙'
);

INSERT INTO HIS_MEDICAL_ORDER VALUES ('CASE-001', 'TEST20260811001', 1, '普外科护理常规，禁食水并观察腹痛变化。');
INSERT INTO HIS_MEDICAL_ORDER VALUES ('CASE-001', 'TEST20260811001', 2, '完善术前检查及麻醉评估。');
INSERT INTO HIS_MEDICAL_ORDER VALUES ('CASE-001', 'TEST20260811001', 3, '给予补液、抗感染及对症处理。');
INSERT INTO HIS_MEDICAL_ORDER VALUES ('CASE-001', 'TEST20260811001', 4, '向患者说明手术与非手术治疗风险。');

INSERT INTO HIS_CHARGE VALUES ('CASE-001', 'TEST20260811001', 1, '血常规检查', 25.00);
INSERT INTO HIS_CHARGE VALUES ('CASE-001', 'TEST20260811001', 2, '腹部超声检查', 120.00);

INSERT INTO HIS_REPORT VALUES ('CASE-001', 'TEST20260811001', 1, '检验', '血常规', '白细胞12.6×10^9/L，中性粒细胞0.84。');
INSERT INTO HIS_REPORT VALUES ('CASE-001', 'TEST20260811001', 2, '影像', '腹部超声', '提示右下腹盲端管状结构增粗。');

INSERT INTO HIS_ENCOUNTER (
  PATIENT_ID, VISIT_ID, HOSPITAL_NAME, PATIENT_NAME, GENDER, AGE, WARD_NAME, BED_NUMBER, INPATIENT_NO,
  ADMITTED_AT, RECORDED_AT, ILLNESS_ONSET_COURSE, PRIMARY_SYMPTOMS, PAST_MEDICAL_HISTORY, PHYSICAL_EXAMINATION,
  DIAGNOSIS_BASIS, DIFFERENTIAL_DIAGNOSIS, CASE_CLASSIFICATION, ATTENDING_PHYSICIAN, AUTHOR_PHYSICIAN
) VALUES (
  'CASE-002', 'TEST20260812002', '示例市第一医院', '患者乙', '女', 54, '呼吸与危重症医学科', '08B', 'TEST20260812002',
  TO_TIMESTAMP_TZ('2026-08-12 09:10:00 +08:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
  TO_TIMESTAMP_TZ('2026-08-12 10:00:00 +08:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
  '患者3天前受凉后出现咳嗽、咳黄痰，伴发热，近1天活动后气促加重，门诊胸部CT提示右下肺炎性改变后收入院。',
  '咳嗽、咳黄痰、发热，活动后气促，无胸痛及咯血。',
  '有高血压病史5年，规律口服降压药；否认糖尿病、慢性肺病及药物过敏史。',
  '体温38.4℃；双肺呼吸音粗，右下肺可闻及湿性啰音，心律齐，腹部平软，无压痛，双下肢无水肿。',
  '急性发热咳嗽咳痰，查体右下肺湿性啰音，炎症指标升高，胸部CT提示右下肺片状实变影。',
  '需与病毒性肺炎、肺结核、肺栓塞及肺部肿瘤继发感染鉴别。',
  '社区获得性肺炎，中危。', '医生丙', '医生丁'
);

INSERT INTO HIS_MEDICAL_ORDER VALUES ('CASE-002', 'TEST20260812002', 1, '呼吸内科护理常规，监测体温、血氧饱和度及呼吸情况。');
INSERT INTO HIS_MEDICAL_ORDER VALUES ('CASE-002', 'TEST20260812002', 2, '留取痰标本行病原学检查，复查血常规及C反应蛋白。');
INSERT INTO HIS_MEDICAL_ORDER VALUES ('CASE-002', 'TEST20260812002', 3, '给予经验性抗感染、祛痰及对症支持治疗。');
INSERT INTO HIS_MEDICAL_ORDER VALUES ('CASE-002', 'TEST20260812002', 4, '必要时低流量吸氧，维持血氧饱和度在目标范围。');

INSERT INTO HIS_CHARGE VALUES ('CASE-002', 'TEST20260812002', 1, '血常规检查', 25.00);
INSERT INTO HIS_CHARGE VALUES ('CASE-002', 'TEST20260812002', 2, 'C反应蛋白检查', 40.00);
INSERT INTO HIS_CHARGE VALUES ('CASE-002', 'TEST20260812002', 3, '胸部CT检查', 280.00);

INSERT INTO HIS_REPORT VALUES ('CASE-002', 'TEST20260812002', 1, '检验', '血常规', '白细胞14.2×10^9/L，中性粒细胞0.86。');
INSERT INTO HIS_REPORT VALUES ('CASE-002', 'TEST20260812002', 2, '检验', 'C反应蛋白', 'C反应蛋白68 mg/L。');
INSERT INTO HIS_REPORT VALUES ('CASE-002', 'TEST20260812002', 3, '影像', '胸部CT', '右下肺见片状实变影及少量磨玻璃影，考虑炎性病变。');

COMMIT;
EXIT SUCCESS;
